# Generated by Django 4.2.4 on 2023-09-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheNumberOfStudentsPerTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("separate", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "number_2000",
                    models.FloatField(blank=True, db_column="2000", null=True),
                ),
                (
                    "number_2001",
                    models.FloatField(blank=True, db_column="2001", null=True),
                ),
                (
                    "number_2002",
                    models.FloatField(blank=True, db_column="2002", null=True),
                ),
                (
                    "number_2003",
                    models.FloatField(blank=True, db_column="2003", null=True),
                ),
                (
                    "number_2004",
                    models.FloatField(blank=True, db_column="2004", null=True),
                ),
                (
                    "number_2005",
                    models.FloatField(blank=True, db_column="2005", null=True),
                ),
                (
                    "number_2006",
                    models.FloatField(blank=True, db_column="2006", null=True),
                ),
                (
                    "number_2007",
                    models.FloatField(blank=True, db_column="2007", null=True),
                ),
                (
                    "number_2008",
                    models.FloatField(blank=True, db_column="2008", null=True),
                ),
                (
                    "number_2009",
                    models.FloatField(blank=True, db_column="2009", null=True),
                ),
                (
                    "number_2010",
                    models.FloatField(blank=True, db_column="2010", null=True),
                ),
                (
                    "number_2011",
                    models.FloatField(blank=True, db_column="2011", null=True),
                ),
                (
                    "number_2012",
                    models.FloatField(blank=True, db_column="2012", null=True),
                ),
                (
                    "number_2013",
                    models.FloatField(blank=True, db_column="2013", null=True),
                ),
                (
                    "number_2014",
                    models.FloatField(blank=True, db_column="2014", null=True),
                ),
                (
                    "number_2015",
                    models.FloatField(blank=True, db_column="2015", null=True),
                ),
                (
                    "number_2016",
                    models.FloatField(blank=True, db_column="2016", null=True),
                ),
                (
                    "number_2017",
                    models.FloatField(blank=True, db_column="2017", null=True),
                ),
                (
                    "number_2018",
                    models.FloatField(blank=True, db_column="2018", null=True),
                ),
                (
                    "number_2019",
                    models.FloatField(blank=True, db_column="2019", null=True),
                ),
                (
                    "number_2020",
                    models.FloatField(blank=True, db_column="2020", null=True),
                ),
                (
                    "number_2021",
                    models.FloatField(blank=True, db_column="2021", null=True),
                ),
                (
                    "number_2022",
                    models.FloatField(blank=True, db_column="2022", null=True),
                ),
            ],
            options={
                "db_table": "the_number_of_students_per_teacher",
                "managed": False,
            },
        ),
    ]
